ingress:
  # reserved in GCP, note that I forgot `r` at the end
  externalIpName: loadbalance-balochistan

web:
  replicasCount: 1

env:
  staticUrl: "https://storage.googleapis.com/static-covid/static/balochistan"
  nodeEnv: "production"
  defaultEpiforChannel: "balochistan"
