INTERVENTION_TYPES = [
    "Mask Wearing",
    "Symptomatic Testing",
    "Gatherings <1000",
    "Gatherings <100",
    "Gatherings <10",
    "Some Businesses Suspended",
    "Most Businesses Suspended",
    "School Closure",
    "Stay Home Order",
    "Travel Screen/Quarantine",
    "Travel Bans",
    "Public Transport Limited",
    "Internal Movement Limited",
    "Public Information Campaigns",
]
