apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  APP_VERSION: {{ .Chart.AppVersion | quote }}
  STATIC_URL: {{ .Values.env.staticUrl | quote }}
  ALLOWED_HOSTS: {{ .Values.ingress.tlsDomainName | quote }}
