apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  APP_REVISION: {{ .Chart.AppVersion | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel }}
  ENABLE_NOTION: {{ .Values.env.enableNotion }}