apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.externalIpName }}
spec:
  rules:
  -  http:
        paths:
        - path: /*
          backend:
            serviceName: {{ .Release.Name }}-web-server
            servicePort: 8000