apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: covid-web-server
spec:
  maxReplicas: 15
  minReplicas: {{ .Values.web.replicasCount }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: covid-web-server
  targetCPUUtilizationPercentage: 70

