FROM continuumio/anaconda3:2020.07

WORKDIR /app

RUN apt-get update && apt-get install -y \
    g++ \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV ENV_NAME=covid

COPY conda-enviroment.yml ./
RUN conda env create -f conda-enviroment.yml

ENV PATH /opt/conda/envs/${ENV_NAME}/bin:$PATH
RUN /bin/bash -c "source activate ${ENV_NAME}"


RUN curl -sSL https://sdk.cloud.google.com | bash
ENV PATH $PATH:/root/google-cloud-sdk/bin

COPY epimodel epimodel
COPY data-dir data-dir
COPY run_luigi luigi.cfg logging.conf secrets.cfg scripts/run_model.sh  ./

ENTRYPOINT ["/bin/bash", "run_model.sh"]