#!/usr/bin/env python
import sys
from luigi.configuration import add_config_path
from luigi.cmdline import luigi_run

if __name__ == "__main__":
    add_config_path("secrets.cfg")
    if "--scheduler-host" in sys.argv[1:]:
        args = ["--module", "epimodel.tasks"] + sys.argv[1:]
    else:
        args = ["--module", "epimodel.tasks", "--local-scheduler"] + sys.argv[1:]
    luigi_run(args)
