name: Compute npi-model and upload

on:
  push:
    branches:
      - 518-npi-model-data-merge
    paths:
      - 'data-pipeline/**'
      - '.github/workflows/compute-npi-model.yml'

jobs:
  NPI-model-computation:
    runs-on: ubuntu-latest
    env:
      RUN_REGION: us-west1-c
      IMAGE_NAME: npi-model

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout data repo
        uses: actions/checkout@v2
        with:
          repository: epidemics/epimodel-covid-data
          path: data-pipeline/data

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        name: Setup Google Cloud Platform
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build Docker
        working-directory: data-pipeline
        run: |
          docker build -t gcr.io/${{ secrets.GKE_PROJECT }}/$IMAGE_NAME:$GITHUB_SHA -f Dockerfile.conda .

      # Push the Docker image to Google Container Registry
      - name: Publish Docker
        run: |
          docker push gcr.io/${{ secrets.GKE_PROJECT }}/$IMAGE_NAME:$GITHUB_SHA

      - name: Run model and upload results
        env:
          GCP_KEY: ${{ secrets.NPI_MODEL_SERVICE_ACCOUNT_KEY }}
        run: |
          gcloud compute instances create-with-container $IMAGE_NAME \
            --zone $RUN_REGION \
            --container-image gcr.io/${{ secrets.GKE_PROJECT }}/$IMAGE_NAME:$GITHUB_SHA \
            --container-env GCP_KEY=$GCP_KEY \
            --container-env FORETOLD_CHANNEL=${{ secrets.FORETOLD_CHANNEL }} \
            --container-arg pavel2 \
            --container-restart-policy never \
            --source-instance-template npi-model-instance-template \
