name: covid

on: [push]

env:
  IMAGE_NAME: covid

jobs:
  check:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Build
      run: |
        yarn install
        yarn run build

    - name: Lint
      run: yarn run lint-check

    - name: Tests
      run: yarn run test
