version: "3"

services:
  server:
    build: .
    networks:
      - caddy
    labels:
      caddy: "epidemics.danielhnyk.cz epidemicforecasting.org"
      caddy.reverse_proxy: "{{upstreams 8000}}"
    #volumes:
    #- ./server/server.ts:/usr/app/server/server.ts
    #- ./server/templates:/usr/app/server/templates
networks:
  caddy:
    external: true
